[server]
host = "127.0.0.1"
port = 2775

[smpp]
system_id = "USSDGateway"
max_connections = 100
connection_timeout = 300

[client_simulator]
enabled = true
host = "127.0.0.1"
port = 9091
system_id = "ForwardingClient"
password = "forward123"
forwarding_clients = ["ForwardingClient", "JavaClient"]

[ussd]
service_codes = ["*123#", "*999#", "*100#", "*199#"]
session_timeout = 180

[ussd.menu]
welcome_message = "Welcome to MyTelecom USSD Service"
main_menu = [
    "1. Balance Inquiry",
    "2. Data Packages",
    "3. Customer Service",
    "0. Exit",
]

[ussd.responses]
balance_message = """
Your current balance is $25.50
Your data balance is 2.5GB"""
invalid_code = "Invalid USSD code. Please try again."
invalid_option = "Invalid option. Please try again."
goodbye_message = "Thank you for using MyTelecom USSD Service. Goodbye!"

[[ussd.data_packages.packages]]
name = "1GB Package"
price = 10.0
data = "1GB"

[[ussd.data_packages.packages]]
name = "5GB Package"
price = 40.0
data = "5GB"

[[ussd.data_packages.packages]]
name = "10GB Package"
price = 70.0
data = "10GB"

[logging]
debug = false
log_file = "server.log"

[response_percentage]
success_percentage = 95.0
failure_percentage = 4.0
no_response_percentage = 1.0
failure_error_code = 0x00000008  # ESME_RSYSERR
no_response_delay_ms = 5000
